<?xml version="1.0" encoding="utf-8"?><Database Name="QLSV" Class="DBPieChartDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-L5HNLU56\SQLEXPRESS;Initial Catalog=QLSV;Integrated Security=True" SettingsObjectName="_20110375_HuynhDangKhoa_LoginForm.Properties.Settings" SettingsPropertyName="QLSVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.totalAgeByView" Member="totalAgeByViews">
    <Type Name="totalAgeByView">
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantitys" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>